### ISSUE TITLE
little help

### ISSUE THREAD

**Issue by publicocean0** [audiocogs/aurora.js#187]
Hi i might realize a class 
with method
appendDataBuffer(rawdata)
seek(time)

how to append binary data from a stream? 
how to seek ?

**Comment by crackofdusk** [comment]
Have you seen the documentation, in particular this section: https://github.com/audiocogs/aurora.js/wiki/Getting-Started#getting-information-about-an-audio-file ?

**Comment by publicocean0** [comment]
Yes i read, i already developped a class 

I dont use typescript so the code is javascript. 

I m in debug because i have a error. It is very strange because the code seams generic and abstract .
The binary blocks are appended ... 
- mp3 is detected
- metadata event is executed 
- now there is a exception in decoder :

```
reading -> 0%
mkv.html:249 Error: Huffman data overrun
    at Layer3.huffmanDecode (mp3.js:5682)
    at Layer3.decodeMainData (mp3.js:5236)
    at Layer3.decode (mp3.js:5083)
    at MP3Frame.decode (mp3.js:365)
    at Class.readChunk (mp3.js:46)
    at Class.Decoder.decode (decoder.js:72)
    at Class.<anonymous> (decoder.js:46)
    at Class.EventEmitter.emit (events.js:64)
    at Class.readChunk (mp3.js:326)
    at StreamSource.<anonymous> (demuxer.js:34)
mkv.html:55 

reading -> 0.4578977240269645%
```

I developped a class similar to FIleSource/HttpSource. I dont know where is the difference.
I used also a internal promise for granting readings are in incremental time.Anyway the error seams in the second block. 
I developped a trial Stream class for reading a file (not websocket). Stream prototype is generic and work  with any datasource.   If you need i pass also FileStream.If i understand correctly is the Source to command the flow if the readings ... not decoder (decoder is passive and can just receive data, it can t command to read a specific chunk). For seeking to a specific time i have to place source in a specific file position and start....


```
	var StreamSource = (function(_super) {
	    __extends = function(child, parent) {
	        var __hasProp = {}.hasOwnProperty
	        for (var key in parent) {
	            if (__hasProp.call(parent, key))
	                child[key] = parent[key];
	        }

	        function ctor() {
	            this.constructor = child;
	        }
	        ctor.prototype = parent.prototype;
	        child.prototype = new ctor();
	        child.__super__ = parent.prototype;
	        return child;
	    };

	    __extends(StreamSource, _super);

	    function StreamSource(stream) {

	        var _this = this,
	            lastRead = Promise.resolve(),
	            playing = false,
	            error = false;


	        var onread = function(b) {
	            if (!playing) return;
	            try {
	                _this.emit('data', new AV.Buffer(new Uint8Array(b.buffer)));
	                console.log(b.offset / stream.getSize() * 100)
	                _this.emit('progress', b.offset / stream.getSize() * 100);
	            } catch (e) {
	                console.error(e);
	                throw e;
	            }


	            if (b.eof) {
	                _this.emit('end');

	            }


	        };

	        var read = function() {
	            lastRead = new Promise(function(r, e) {
	                if (playing) {
	                    lastRead.then(function() {
	                        stream.read().then(function(result) {

	                            onread(result);
	                            if (!result.eof && playing) read();
	                            r();
	                        });
	                    }).catch(function(err) {
	                        error = true;
	                        _this.emit("error", ((err) ? err : 'unknown error'));
	                    });


	                }

	            });

	        };

	        this.start = function() {
	            if (playing) return;
	            playing = true;
	            read();
	            return false;
	        }

	        this.pause = function() {
	            if (!playing) return;
	            playing = false;
	            return false;
	        }

	        this.reset = function() {
	            playing = false;

	            if (error) {
	                error = false;
	                lastRead = Promise.resolve();
	            } else lastRead = new Promise(function(s, e) {
	                lastRead.then(function() {
	                    lastRead = Promise.resolve();
	                    s();

	                }).catch(function() {
	                    lastRead = Promise.resolve();
	                    s();
	                });

	            })
	            return false;
	        }
	    }




	    return StreamSource;

	})(AV.EventEmitter);
	
```

**Comment by publicocean0** [comment]
**Additional tests(decode data connected to audiocontext destination**,just Asset class,no player ):
- addiing a timer 2secs every read for understaning if it is a problem about processes conflict . No it is not this(same exception)
- tried to execute FileSource from window context (not inside typescript clousures as my class) but filesource has the same behaviour(it works anyway). 
- tried to see the buffers appened , they are not the same ... so there is no error in duplications
- using the same mp3 read by default fileSource i can listen the music.
- using a different mp3 file read by my stream source there is no exception but decoder emits wrong data (rumors not music)
- using filesource and streamsource no data decoded using this mp3 https://soundcloud.com/theokouroumlis/breathe-in (general error)
- i tried to change chunk size in stream source... from 40k to 1k ... there is the error 
https://github.com/audiocogs/aurora.js/issues/188 and then is called pause. 
 

**Additional tests(using av.player**):
- Using Av.Player mp3 works with filesource. Using streamsource it seams work just for first block then music stopped. Maybe the loop inside soource must be synchonous?  In that case using promise i can t use it

**Comment by publicocean0** [comment]
By my tests there is the following result:
Bugs:
 1: #188  it appear with streamsource and also with filesource. The error block the stream in some case. Hacking the pause call for not blocking the stream .... i can hear the music. 

2:  Huffman data overrun
 ```
   at Layer3.huffmanDecode (mp3.js:5682)
    at Layer3.decodeMainData (mp3.js:5236)
    at Layer3.decode (mp3.js:5083)
    at MP3Frame.decode (mp3.js:365)
    at Class.readChunk (mp3.js:46)
    at Class.Decoder.decode (decoder.js:72)
    at Class.<anonymous> (decoder.js:46)
    at Class.EventEmitter.emit (events.js:64)
    at Class.readChunk (mp3.js:326)
    at StreamSource.<anonymous> (demuxer.js:34)
```

 appear if the chunk is smaller than a specific size. But the beahviour might be indipedent by chunk size. I saw the confirmation changing the chunkSize in your code.

3: there is a emprovement to do in when you start the file reader  in sourcefile. It can happen you execute start call when the pending reading is not completed (fast pause+start events). `file.coffee:47 Uncaught DOMException: Failed to execute 'readAsArrayBuffer' on 'FileReader': The object is already busy reading Blobs.
    at FileSource.loop (file:///home/cristian/temp/js/mkv/aurora.js:3766:24)
    at FileSource.start (file:///home/cristian/temp/js/mkv/aurora.js:3723:21)
    at Asset.start (file:///home/cristian/temp/js/mkv/aurora.js:74:19)
    at file:///home/cristian/temp/js/mkv/mkv.html:239:7
    at AudioBufferSourceNode.source.onended (file:///home/cristian/temp/js/mkv/mkv.html:164:5)`



i can resolve 3 easily, skip point 2 setting chunk size (1<<20) ... but point 1 are in decoder... the code is not so simple .
