### ISSUE TITLE
gyp build fail

### ISSUE THREAD

**Issue by nickveliki** [audiocogs/aurora.js#217]
I can build most projects no problem but I can't seem to get yours going

binding.target.mk:122: recipe for target 'Release/obj.target/binding/src/binding.o' failed
make: *** [Release/obj.target/binding/src/binding.o] Error 1
make: Leaving directory '/home/nickveliki/avtest/node_modules/speaker/build'
gyp ERR! build error
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:194:23)
gyp ERR! stack     at ChildProcess.emit (events.js:321:20)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:275:12)
gyp ERR! System Linux 4.4.0-18362-Microsoft
gyp ERR! command "/usr/local/bin/node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /home/nickveliki/avtest/node_modules/speaker
gyp ERR! node -v v13.8.0
gyp ERR! node-gyp -v v5.0.5
gyp ERR! not ok

**Comment by niemes** [comment]
Hi, Its seems Node-speaker need to be update to work with node v12.x.x
[node speaker build issue 0.3](https://github.com/TooTallNate/node-speaker/issues/83)
